all: html

SPHINX_PROJECT_NAME = Embedded Webserver Demo (No SPI Flash) Quickstart Guide
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../app_webserver_demo
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
